# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Domain Tool

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - .github/**
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - .github/**
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build domain tool
      run: go build -v -o domaintool && mv domaintool bin/

    - name: Build domain tool updater
      run: cd domain-tool-updater && go build -v -o domain-tool-updater && mv domain-tool-updater ../bin/

    - name: Test
      run: go test -v ./main.go

    - name: Upload an Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
    # Artifact name
        name: binaries # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: |
          bin/domaintool
          bin/domain-tool-updater
        retention-days: 2
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: binaries
          path: bin/
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          push: true
          tags: user/domain-tool:latest
        
        
